services:
  - type: web
    name: report-nlp-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash src/start.sh"
    envVars:
      - key: PORT
        value: 10000
